# Generated by Django 3.2.9 on 2021-11-12 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('recordDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('soundUrl', models.CharField(max_length=200)),
                ('imgUrl', models.CharField(max_length=200)),
            ],
        ),
    ]
