# Generated by Django 3.2.5 on 2021-12-03 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecordSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('recordDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('soundUrl', models.CharField(max_length=200)),
                ('imgUrl1', models.CharField(max_length=200, null=True)),
                ('imgUrl2', models.CharField(max_length=200, null=True)),
                ('imgUrl3', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
