# Generated by Django 3.2.5 on 2021-12-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordSound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordsound',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='recordsound',
            name='imgUrl1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recordsound',
            name='imgUrl2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recordsound',
            name='imgUrl3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
